/****** Script for SelectTopNRows command from SSMS  ******/
SELECT  o.[OrderID]
      ,o.[CustomerID]
      ,o.[EmployeeID]
      ,o.[OrderDate]
      ,o.[RequiredDate]
      ,o.[ShippedDate]
      ,o.[ShipVia]
	  ,s.[CompanyName]
      ,o.[Freight]
      ,o.[ShipName]
      ,o.[ShipAddress]
      ,o.[ShipCity]
      ,o.[ShipRegion]
      ,o.[ShipPostalCode]
      ,o.[ShipCountry]
   FROM [Northwind].[dbo].[Orders]o JOIN  [Northwind].[dbo].[Shippers] s on o.[ShipVia] = s.[ShipperID]